name: box_familia
description: "Application Flutter offline-first avec Drift et synchronisation MVP."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.33.0
  drift_flutter: ^0.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1

  # Prévu pour la prochaine étape Google Drive.
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  drift_dev: ^2.33.0

flutter:
  uses-material-design: true
