// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZyY-82YLjwQwV4dAmUTKHDYLYG14mDj4',
    appId: '1:836905993125:web:f43ccba66be0a1db645e4c',
    messagingSenderId: '836905993125',
    projectId: 'box-familia',
    authDomain: 'box-familia.firebaseapp.com',
    storageBucket: 'box-familia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKxOlfZ_ALMGjRw2xAUeBYaaeYe-dw9oc',
    appId: '1:836905993125:android:db1e389b4999e1f1645e4c',
    messagingSenderId: '836905993125',
    projectId: 'box-familia',
    storageBucket: 'box-familia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUEIjzIddr_UvvgSw-Ly6dug2BXeL2ED0',
    appId: '1:836905993125:ios:dc4a50b1f9baec7e645e4c',
    messagingSenderId: '836905993125',
    projectId: 'box-familia',
    storageBucket: 'box-familia.firebasestorage.app',
    iosBundleId: 'com.example.boxFamilia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUEIjzIddr_UvvgSw-Ly6dug2BXeL2ED0',
    appId: '1:836905993125:ios:dc4a50b1f9baec7e645e4c',
    messagingSenderId: '836905993125',
    projectId: 'box-familia',
    storageBucket: 'box-familia.firebasestorage.app',
    iosBundleId: 'com.example.boxFamilia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZyY-82YLjwQwV4dAmUTKHDYLYG14mDj4',
    appId: '1:836905993125:web:b47f672e083b5907645e4c',
    messagingSenderId: '836905993125',
    projectId: 'box-familia',
    authDomain: 'box-familia.firebaseapp.com',
    storageBucket: 'box-familia.firebasestorage.app',
  );
}
